SELECT DISTINCT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY
     , SUM(SALES * PRICE) OVER(PARTITION BY A.AUTHOR_ID, CATEGORY) AS TOTAL_SALES
  FROM BOOK A
  JOIN AUTHOR B
    ON A.AUTHOR_ID = B.AUTHOR_ID
  JOIN (SELECT DISTINCT BOOK_ID, SUM(SALES) OVER(PARTITION BY BOOK_ID) AS SALES
          FROM BOOK_SALES A
         WHERE EXTRACT(YEAR FROM SALES_DATE) = 2022
           AND EXTRACT(MONTH FROM SALES_DATE) = 1) C
    ON A.BOOK_ID = C.BOOK_ID
 ORDER BY AUTHOR_ID, CATEGORY DESC;