SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, 
       EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
       GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
  FROM ONLINE_SALE A
  JOIN USER_INFO B
    ON A.USER_ID = B.USER_ID
 WHERE GENDER IS NOT NULL
 GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER
 ORDER BY YEAR, MONTH, GENDER