SELECT CAR_ID,CAR_TYPE,FEE
FROM (
SELECT 
        CAR_ID,CAR_TYPE
      , (DAILY_FEE-((DAILY_FEE/100)*(SELECT MAX(DISCOUNT_RATE) 
         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN C 
        WHERE C.CAR_TYPE = A.CAR_TYPE
         AND duration_type LIKE '30일%')))*30 AS FEE 
FROM CAR_RENTAL_COMPANY_CAR A
WHERE CAR_ID NOT IN (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE 1=1
AND ((TO_CHAR(START_DATE,'YYYYMMDD') BETWEEN '20221101' AND '20221131' )
    OR (TO_CHAR(END_DATE,'YYYYMMDD') BETWEEN '20221101' AND '20221131' ))
 OR ((TO_CHAR(START_DATE,'YYYYMMDD') < '20221101') AND (TO_CHAR(END_DATE,'YYYYMMDD') > '20221130')))
AND CAR_TYPE IN ('SUV','세단'))
WHERE  1=1
AND FEE >= 500000 
AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC