SELECT ANIMAL_ID, NAME
  FROM (
        SELECT I.ANIMAL_ID, I.NAME
               , ROW_NUMBER() OVER(ORDER BY TO_NUMBER(TO_CHAR(O.DATETIME, 'YYYYMMDD')) - TO_NUMBER(TO_CHAR(I.DATETIME, 'YYYYMMDD')) DESC) AS ROW_NO
          FROM ANIMAL_INS I
          JOIN ANIMAL_OUTS O
            ON I.ANIMAL_ID = O.ANIMAL_ID
       )
 WHERE ROW_NO <= 2;