SELECT *
  FROM
(SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR, 
        TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH, 
 COUNT(DISTINCT A.USER_ID) OVER(PARTITION BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM')) AS PUCHASED_USERS,
 ROUND((COUNT(DISTINCT A.USER_ID) OVER(PARTITION BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM')) /   B.ALL_USER), 1) AS PUCHASED_RATIO
  FROM ONLINE_SALE A
  JOIN
      (
       SELECT USER_ID, COUNT(*) OVER() AS ALL_USER
         FROM USER_INFO
        WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
      ) B
    ON A.USER_ID = B.USER_ID
 WHERE SALES_AMOUNT > 0)
 GROUP BY YEAR, MONTH, PUCHASED_USERS, PUCHASED_RATIO
 ORDER BY YEAR, MONTH