SELECT *
  FROM
    (SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, 
            EXTRACT(MONTH FROM SALES_DATE) AS MONTH, 
            COUNT(DISTINCT A.USER_ID) 
            OVER(PARTITION BY EXTRACT(YEAR FROM SALES_DATE),EXTRACT(MONTH FROM SALES_DATE)) AS PUCHASED_USERS,
            ROUND(
              (COUNT(DISTINCT A.USER_ID) 
              OVER(PARTITION BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)) / B.ALL_USER)
              , 1) AS PUCHASED_RATIO
      FROM ONLINE_SALE A
      JOIN
          (
           SELECT USER_ID, COUNT(*) OVER() AS ALL_USER
             FROM USER_INFO
            WHERE EXTRACT(YEAR FROM JOINED) = 2021
          ) B
        ON A.USER_ID = B.USER_ID
     WHERE SALES_AMOUNT > 0)
 GROUP BY YEAR, MONTH, PUCHASED_USERS, PUCHASED_RATIO
 ORDER BY YEAR, MONTH