SELECT TB1.ITEM_ID
     , ITEM_NAME
     , RARITY
  FROM ITEM_INFO TB1
  JOIN (SELECT ITEM_ID
          FROM ITEM_TREE A
         WHERE NOT EXISTS (
            SELECT 1
              FROM ITEM_TREE B
             WHERE A.ITEM_ID = B.PARENT_ITEM_ID)
       ) TB2
    ON TB1.ITEM_ID = TB2.ITEM_ID
 ORDER BY ITEM_ID DESC;