SELECT DISTINCT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) OVER(PARTITION BY PRODUCT_CODE) AS SALES
  FROM PRODUCT A
  JOIN OFFLINE_SALE B
    ON A.PRODUCT_ID = B.PRODUCT_ID
 ORDER BY SALES DESC, PRODUCT_CODE;