SELECT CAR_ID, CAR_TYPE, FEE
  FROM (
SELECT A.CAR_ID, A.CAR_TYPE, TRUNC((1 - 0.01 * DISCOUNT_RATE) * DAILY_FEE * 30, 0) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
  JOIN (SELECT DISTINCT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
         WHERE NOT EXISTS (SELECT 1
                             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY D
                            WHERE B.CAR_ID = D.CAR_ID
                              AND ((TO_CHAR(START_DATE, 'YYYYMMDD') BETWEEN '20221101' AND '20221130'
                               OR TO_CHAR(END_DATE, 'YYYYMMDD') BETWEEN '20221101' AND '20221130')
                               OR (TO_CHAR(START_DATE, 'YYYYMMDD') < '20221101'
                                   AND TO_CHAR(END_DATE, 'YYYYMMDD') > '20221130'))
                  )) B
    ON A.CAR_ID = B.CAR_ID
  JOIN (SELECT CAR_TYPE, DISCOUNT_RATE
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
         WHERE CAR_TYPE IN ('세단', 'SUV')
           AND INSTR(DURATION_TYPE, 30) > 0) C
    ON A.CAR_TYPE = C.CAR_TYPE)
 WHERE FEE >= 500000
   AND FEE < 2000000
 ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
