SELECT HOUR, COUNT(A.DATETIME) AS COUNT
  FROM (SELECT LEVEL - 1 AS HOUR
          FROM DUAL
       CONNECT BY LEVEL <= 24) B
  LEFT OUTER JOIN ANIMAL_OUTS A
    ON TO_CHAR(A.DATETIME, 'HH24') = B.HOUR
 GROUP BY HOUR
 ORDER BY HOUR