WITH RANKED_DATA AS (
  SELECT ID, 
         ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RNK,
         COUNT(*) OVER() AS CNT
    FROM ECOLI_DATA
)
SELECT A.ID,
       CASE 
         WHEN B.RNK <= FLOOR(B.CNT * 0.25) THEN 'CRITICAL'
         WHEN B.RNK <= FLOOR(B.CNT * 0.5) THEN 'HIGH'
         WHEN B.RNK <= FLOOR(B.CNT * 0.75) THEN 'MEDIUM'
         ELSE 'LOW'
       END AS COLONY_NAME
  FROM ECOLI_DATA A
  JOIN RANKED_DATA B
    ON A.ID = B.ID
 ORDER BY A.ID;
