SELECT DISTINCT USER_ID
     , NICKNAME
     , CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2 AS "전체주소"
     , SUBSTR(TLNO, 1, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8) AS "전화번호"
  FROM USED_GOODS_USER A
  JOIN (SELECT WRITER_ID, COUNT(*) OVER(PARTITION BY WRITER_ID) AS CNT
          FROM USED_GOODS_BOARD) B
    ON A.USER_ID = B.WRITER_ID
 WHERE B.CNT >= 3
 ORDER BY USER_ID DESC;