SELECT DISTINCT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS
     , ROUND(AVG(B.REVIEW_SCORE) OVER(PARTITION BY B.REST_ID), 2) AS SCORE
  FROM REST_INFO A
  JOIN REST_REVIEW B
    ON A.REST_ID = B.REST_ID
 WHERE SUBSTR(ADDRESS, 0, 2) = '서울'
 ORDER BY SCORE DESC, FAVORITES DESC;