SELECT DISTINCT EXTRACT(YEAR FROM B.SALES_DATE) AS YEAR
     , EXTRACT(MONTH FROM B.SALES_DATE) AS MONTH
     , A.GENDER
     , COUNT(DISTINCT A.USER_ID) OVER(PARTITION BY EXTRACT(YEAR FROM B.SALES_DATE)
                                , EXTRACT(MONTH FROM B.SALES_DATE)
                                , A.GENDER) AS USERS
  FROM USER_INFO A
  JOIN ONLINE_SALE B
    ON A.USER_ID = B.USER_ID
 WHERE A.GENDER IS NOT NULL
 ORDER BY 1, 2, 3;