SELECT A.FLAVOR
  FROM FIRST_HALF A
  JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) TOT
          FROM JULY
         GROUP BY FLAVOR) B
    ON A.FLAVOR = B.FLAVOR
 ORDER BY A.TOTAL_ORDER + B.TOT DESC FETCH NEXT 3 ROWS ONLY;