SELECT USER_ID, NICKNAME, B.TT AS TOTAL_SALES
  FROM USED_GOODS_USER A
  JOIN
(SELECT WRITER_ID, SUM(PRICE) AS TT
   FROM USED_GOODS_BOARD
  WHERE STATUS = 'DONE'
  GROUP BY WRITER_ID
 HAVING SUM(PRICE) >= 700000) B
   ON USER_ID = WRITER_ID
 ORDER BY TOTAL_SALES;