SELECT *
  FROM 
   (
    SELECT DISTINCT USER_ID, NICKNAME, SUM(PRICE) OVER(PARTITION BY USER_ID) AS TOTAL_SALES
      FROM USED_GOODS_USER A
      JOIN USED_GOODS_BOARD B
        ON A.USER_ID = B.WRITER_ID
     WHERE STATUS = 'DONE'
    )
 WHERE TOTAL_SALES >= 700000
 ORDER BY TOTAL_SALES;