SELECT DISTINCT CAR_TYPE, COUNT(*) OVER(PARTITION BY CAR_TYPE) AS CARS
  FROM CAR_RENTAL_COMPANY_CAR A
 WHERE EXISTS (SELECT 1
                 FROM CAR_RENTAL_COMPANY_CAR B
                WHERE A.CAR_ID = B.CAR_ID
                  AND INSTR(OPTIONS, '시트') > 1)
 ORDER BY CAR_TYPE;