SELECT EXTRACT(YEAR FROM SALES_DATE) YEAR, EXTRACT(MONTH FROM SALES_DATE) MONTH
     , COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS
     , ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = 2021), 1) AS PUCHASED_RATIO
  FROM USER_INFO A
  JOIN ONLINE_SALE B
    ON A.USER_ID = B.USER_ID
 WHERE EXTRACT(YEAR FROM JOINED) = 2021
 GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
 ORDER BY YEAR, MONTH;