SELECT NAME, DATETIME
  FROM ANIMAL_INS A
 WHERE NOT EXISTS (SELECT 1
                     FROM ANIMAL_OUTS B
                    WHERE A.ANIMAL_ID = B.ANIMAL_ID
                      AND B.DATETIME IS NOT NULL)
 ORDER BY DATETIME ASC FETCH NEXT 3 ROWS ONLY;