SELECT DISTINCT AUTHOR_ID, AUTHOR_NAME, CATEGORY
     , SUM(MULTI) OVER(PARTITION BY AUTHOR_ID, AUTHOR_NAME, CATEGORY) AS TOTAL_SALES
  FROM 
  (
    SELECT A.BOOK_ID, CATEGORY, A.AUTHOR_ID, AUTHOR_NAME, PRICE * SALES AS MULTI
      FROM BOOK A
      JOIN AUTHOR B
        ON A.AUTHOR_ID = B.AUTHOR_ID
      JOIN BOOK_SALES C
        ON A.BOOK_ID = C.BOOK_ID
     WHERE EXTRACT(YEAR FROM SALES_DATE) = 2022
       AND EXTRACT(MONTH FROM SALES_DATE) = 1
  )
 ORDER BY AUTHOR_ID, CATEGORY DESC;