SELECT DISTINCT B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY
     , SUM(PRICE * SALES) OVER(PARTITION BY B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY) AS TOTAL_SALES
  FROM BOOK_SALES A
  JOIN BOOK B
    ON A.BOOK_ID = B.BOOK_ID
  JOIN AUTHOR C
    ON B.AUTHOR_ID = C.AUTHOR_ID
 WHERE EXTRACT(YEAR FROM SALES_DATE) = 2022
   AND EXTRACT(MONTH FROM SALES_DATE) = 1
 ORDER BY B.AUTHOR_ID, CATEGORY DESC;