SELECT A.PRODUCT_ID, PRODUCT_NAME, B.TOTAL * PRICE AS TOTAL_SALES
  FROM FOOD_PRODUCT A
  JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL
           FROM FOOD_ORDER
          WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
          GROUP BY PRODUCT_ID) B
    ON A.PRODUCT_ID = B.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;