SELECT TITLE, B.BOARD_ID, REPLY_ID, A.WRITER_ID, A.CONTENTS, DATE_FORMAT(A.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
  FROM USED_GOODS_REPLY A
  JOIN USED_GOODS_BOARD B
    ON A.BOARD_ID = B.BOARD_ID
 WHERE DATE_FORMAT(B.CREATED_DATE, '%Y%m') = '202210'
 ORDER BY A.CREATED_DATE, TITLE;