SELECT USER_ID, NICKNAME, TOTAL_SALES
  FROM USED_GOODS_USER A
  JOIN (SELECT DISTINCT WRITER_ID, SUM(PRICE) OVER(PARTITION BY WRITER_ID) AS TOTAL_SALES
          FROM USED_GOODS_BOARD
         WHERE STATUS = 'DONE') B
    ON A.USER_ID = B.WRITER_ID
 WHERE TOTAL_SALES >= 700000
 ORDER BY TOTAL_SALES;