SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
  FROM MEMBER_PROFILE A
  JOIN REST_REVIEW B
    ON A.MEMBER_ID = B.MEMBER_ID
  JOIN (SELECT MEMBER_ID, COUNT(REVIEW_ID) CNT
          FROM REST_REVIEW
         GROUP BY MEMBER_ID
         ORDER BY CNT DESC FETCH NEXT 1 ROW ONLY) C
    ON A.MEMBER_ID = C.MEMBER_ID
 ORDER BY REVIEW_DATE, REVIEW_TEXT;