SELECT TB1.ITEM_ID, ITEM_NAME, RARITY
  FROM ITEM_INFO TB1
  JOIN (SELECT A.ITEM_ID
          FROM ITEM_TREE A
          JOIN (SELECT ITEM_ID
                  FROM ITEM_INFO
                 WHERE RARITY = 'RARE') B
            ON A.PARENT_ITEM_ID = B.ITEM_ID) TB2
    ON TB1.ITEM_ID = TB2.ITEM_ID
 ORDER BY 1 DESC;