SELECT DISTINCT MCDP_CD AS "진료과 코드", COUNT(APNT_NO) OVER(PARTITION BY MCDP_CD) AS "5월예약건수"
  FROM APPOINTMENT
 WHERE EXTRACT(YEAR FROM APNT_YMD) = 2022
   AND EXTRACT(MONTH FROM APNT_YMD) = 5
 ORDER BY 2, 1;