SELECT DISTINCT EXTRACT(MONTH FROM START_DATE) AS MONTH, A.CAR_ID
     , COUNT(*) OVER(PARTITION BY EXTRACT(MONTH FROM START_DATE), A.CAR_ID) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
  JOIN (SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
         WHERE START_DATE BETWEEN TO_DATE('202208', 'YYYYMM') AND LAST_DAY(TO_DATE('202210', 'YYYYMM'))
         GROUP BY CAR_ID
        HAVING COUNT(*) >= 5) B
    ON A.CAR_ID = B.CAR_ID
 WHERE EXTRACT(MONTH FROM START_DATE) BETWEEN 8 AND 10
 ORDER BY MONTH, CAR_ID DESC;