SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
  JOIN
(
SELECT CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE TO_NUMBER(TO_CHAR(START_DATE, 'MM')) BETWEEN 8 AND 10
 GROUP BY CAR_ID
HAVING COUNT(CAR_ID) >= 5
) B
    ON A.CAR_ID = B.CAR_ID
 WHERE TO_CHAR(START_DATE, 'MM') BETWEEN 8 AND 10
 GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'MM')), A.CAR_ID
 ORDER BY MONTH, A.CAR_ID DESC;