SELECT SCORE, A.EMP_NO, EMP_NAME, POSITION, EMAIL
  FROM HR_EMPLOYEES A
  JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE
          FROM HR_GRADE 
         WHERE YEAR = 2022
         GROUP BY EMP_NO, YEAR
         ORDER BY SCORE DESC LIMIT 1) B
    ON A.EMP_NO = B.EMP_NO