-- 코드를 입력하세요
SELECT r.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
ROUND((SELECT AVG(REVIEW_SCORE) FROM REST_REVIEW rr WHERE rr.REST_ID = i.REST_ID GROUP BY REST_ID ), 2) AS SCORE
FROM REST_INFO i
JOIN REST_REVIEW r ON r.REST_ID = i.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY r.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC