SELECT DISTINCT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, 
                ADDRESS, ROUND(AVG(REVIEW_SCORE) OVER(PARTITION BY A.REST_ID), 2) AS SCORE
  FROM REST_INFO A
  JOIN REST_REVIEW B
    ON A.REST_ID = B.REST_ID
 WHERE SUBSTR(ADDRESS, 1, 2) = '서울'
 ORDER BY SCORE DESC, FAVORITES DESC;